### ISSUE TITLE
Implement new dashboard design

### ISSUE THREAD

**Issue by sazid** [AutomationSolutionz/Framework_0.1#244]
The dashboard design has to be replaced with a new one.

**Comment by m3thun** [comment]
@riz-hossain I'm closing this one without copying it because this ticket is almost a year and half old and substantial design changes have already been implemented.

**Comment by riz-hossain** [comment]
Yes. Feel free to close ticket if you don't think it's needed. I will simply verify them one more time                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: mithunSent: Thursday, September 3, 2015 12:03 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Implement new dashboard design (#244)@riz-hossain I'm closing this one without copying it because this ticket is almost a year and half old and substantial design changes have already been implemented.

—Reply to this email directly or view it on GitHub.
