### ISSUE TITLE
Verification point needs to select repeatedly during edit and verification slider needs to be done.

### ISSUE THREAD

**Issue by Taitalus** [AutomationSolutionz/Framework_0.1#353]
@riz-hossain  vai this is a mere UI problem. I have seen the verification point slider I guess @sazid  or @minar09  can help.

**Comment by riz-hossain** [comment]
Who is looking into this?   Minar can you fix the issue asap.  Someone is gonna demo this in their company today using our website.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Raju Ahmed ShetuSent: Sunday, January 25, 2015 3:21 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: [Framework_0.1] Verification point needs to select repeatedly during edit and verification slider needs to be done. (#353)@riz-hossain  vai this is a mere UI problem. I have seen the verification point slider I guess @sazid  or @minar09  can help.

—Reply to this email directly or view it on GitHub.

**Comment by minar09** [comment]
Well, solved the again clicking problem in edit view. Now seeing the font problem.

The bug was there nothing but using a slightly changed instruction during edit view other than the instruction given in the plugin. And the function needed to use was the same not wrong but used with quotations. That was the problem which could not trigger the data.

Now then I used the function as it was given in the plugin, data fetching seems okay.

Toggle-slider font and sizing is not responsive. So now I am looking into it.
