### ISSUE TITLE
feature implementation logic change to avoid changing of data

### ISSUE THREAD

**Issue by minar09** [AutomationSolutionz/Framework_0.1#355]
It seems it would take some time as the feature implemented in test case creation field and others is a complicated one. So I am opening an issue for it as discussed.

So the logic will be to fetch feature id along with feature path from DB so that we can always get the feature path directly from feature ID but not from the path list saved in DB, so we can avoid of changing data. We can keep the feature id hidden in the ui, and show the path only, but we will fetch the path from DB according to feature id from the product_features table.

Another thing we could do is that, when the feature path changes as the bug happens, it doesn't stay in its lowest folder but show the required field checker color as green, which is wrong. So we could check from DB before showing the green signal whether the path shown is in its lowest folder or not.

**Comment by riz-hossain** [comment]
I think id method would always make sure that at least on the storage point it always works. For example right now we somehow store an invalid path, thus invalid Id, which will never happen when we go by Id.We basically ignore what the ui has once we track by id only.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Matiur Rahman MinarSent: Wednesday, January 28, 2015 12:53 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Subject: [Framework_0.1] feature implementation logic change to avoid changing of data (#355)It seems it would take some time as the feature implemented in test case creation field and others is a complicated one. So I am opening an issue for it as discussed.

So the logic will be to fetch feature id along with feature path from DB so that we can always get the feature path directly from feature ID but not from the path list saved in DB, so we can avoid of changing data. We can keep the feature id hidden in the ui, and show the path only, but we will fetch the path from DB according to feature id from the product_features table.

Another thing we could do is that, when the feature path changes as the bug happens, it doesn't stay in its lowest folder but show the required field checker color as green, which is wrong. So we could check from DB before showing the green signal whether the path shown is in its lowest folder or not.

—Reply to this email directly or view it on GitHub.

**Comment by minar09** [comment]
What I found after searching till now, we may somehow tackle the situation by saving the feature by its id, but when it comes down to showing up properly, I have to say maybe there is something wrong with the codes used show the path in edit view, which sometimes show properly, sometimes doesn't. 

So even if we manage by id, we have to look through the codes for showing the proper path, which looks kinda complicated to me now.

**Comment by riz-hossain** [comment]
Yes. The ui may be messed up a little.. but for time being I think we can survive. In most cases users will have no more than 2 level. Even with current bug it's harder to reproduce when we have 3 level. 4th level it's easier to reproduce.  One other thing we can do is have a pop up window and show the same tree structure that sazid has for view and organize (just the tree view). Sazid would it be a hard to do?                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Matiur Rahman MinarSent: Wednesday, January 28, 2015 4:29 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] feature implementation logic change to avoid changing of data (#355)What I found after searching till now, we may somehow tackle the situation by saving the feature by its id, but when it comes down to showing up properly, I have to say maybe there is something wrong with the codes used show the path in edit view, which sometimes show properly, sometimes doesn't. 

So even if we manage by id, we have to look through the codes for showing the proper path, which looks kinda complicated to me now.

—Reply to this email directly or view it on GitHub.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
