### ISSUE TITLE
In Run Page , the objective will be like milestone

### ISSUE THREAD

**Issue by Taitalus** [AutomationSolutionz/Framework_0.1#431]
after selection the test objective should not be in the selected box rather than it will be like how the milestone selected.

**Comment by m3thun** [comment]
@riz-hossain A highest priority bug that is 6 months old? Please check and update the labels, if needed.

**Comment by riz-hossain** [comment]
This is actually a feature request and that's why it is getting pushed down.  Currently you cannot remove any Objective.. Once it's entered it's there forever. That's why it got high priority.  Also there is no way to manage Objective. This goes to Minar                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: mithunSent: Wednesday, August 19, 2015 12:32 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] In Run Page , the objective will be like milestone (#431)@riz-hossain A highest priority bug that is 6 months old? Please check and update the labels, if needed.

—Reply to this email directly or view it on GitHub.

**Comment by m3thun** [comment]
@riz-hossain copied and closing!
