### ISSUE TITLE
Send email did not work for particular email address

### ISSUE THREAD

**Issue by matariq** [AutomationSolutionz/Framework_0.1#511]
Working fine with gmail

**Comment by riz-hossain** [comment]
thats an odd one.. lets do this later ... first lets fix up all the ui for the framework

**Comment by matariq** [comment]
Actually gmail didnt work either - need to figure out why the report was not send to more than one user.

**Comment by matariq** [comment]
@adeelrehman007 you are still not getting emails from framework correct?

Can you add the details to this bug?

**Comment by adeelrehman007** [comment]
I'm not getting emails to either my hotmail account or gmail. Wondering if
it's the issue is due to any special characters.

Hotmail address has an underscore in it (adeel_rehi@hotmail.com) whereas
the gmail one has three dots (m.adeel.r.mian@gmail.com)

Beyond this I don't have much to add on this.

**Comment by riz-hossain** [comment]
On the new server email service was not started (most likely)                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: AdeelSent: Wednesday, August 26, 2015 10:20 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Send email did not work for particular email address (#511)I'm not getting emails to either my hotmail account or gmail. Wondering if
it's the issue is due to any special characters.

Hotmail address has an underscore in it (adeel_rehi@hotmail.com) whereas
the gmail one has three dots (m.adeel.r.mian@gmail.com)

Beyond this I don't have much to add on this.
On Wed, Aug 26, 2015 at 10:10 AM matariq <notifications@github.com> wrote:

> @adeelrehman007 <https://github.com/adeelrehman007> you are still not
> getting emails from framework correct?
>
> Can you add the details to this bug?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AutomationSolutionz/Framework_0.1/issues/511#issuecomment-135034764>
> .
>


—Reply to this email directly or view it on GitHub.

**Comment by matariq** [comment]
I was getting emails.

This has been an old issue.
