### ISSUE TITLE
Requirement/Task -> Search - How can I edit/delete a task/requirement

### ISSUE THREAD

**Issue by matariq** [AutomationSolutionz/Framework_0.1#536]
Just like TCs - I should be able to edit/delete Requirement/Task

**Comment by riz-hossain** [comment]
Deleting requirement ,task, bug could have a complex implication. Normally in other tools they don't allow deleting it... MKS or jira, you cannot permanently delete something. By default we were gonna hide the completed requirements.  ‎ Or maybe we can create a field "de-scoped"? We will be adding similar filter that you see in result page of test case execution. So you will be able to create your own query and save them and set one to default and such. Mainly because once task and other test cases are linked, they will become orphan. And it will screw up our milestone and few other reporting features that we will be implementing in near future.  You can always Edit and Change things around... Even for test case delete, MKS for example never allowed you to delete a test case. We had to do a lot of extra work to implement test case delete. We actually take snap shot of the test case and make a backup of it and then run it off the backup test case... so that when you delete it, it will go away from main repo but will still exists for your previous runs that you ran. So all our reporting and run history stays intact. Also we will allow "undo delete" in future from this. This is just an example of how delete can adversely impact your over all product and cause a lot of side effects that can really screw up other components.  ‎Edit... you should just be able to view search page and select the item and update it... that should work.  It doesn't work that way?                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: matariqSent: Saturday, July 11, 2015 2:35 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Subject: [Framework_0.1] Requirement/Task -> Search - How can I edit/delete a task/requirement (#536)Just like TCs - I should be able to edit/delete Requirement/Task

—Reply to this email directly or view it on GitHub.

**Comment by matariq** [comment]
I see what you mean why deleting should not be an option.

But can we add "pencil" and "copy" button on the side like TC to keep it consistent user experience?

**Comment by riz-hossain** [comment]
Yes. That we should definitely do. I am not sure if you created a task for that. If not please create one and we can close this ticket.                                                                                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: matariqSent: Saturday, July 11, 2015 3:01 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Requirement/Task -> Search - How can I edit/delete a task/requirement (#536)I see what you mean why deleting should not be an option.

But can we add "pencil" and "copy" button on the side like TC to keep it consistent user experience? 

—Reply to this email directly or view it on GitHub.

**Comment by matariq** [comment]
Closing Ticket
