### ISSUE TITLE
Milestone in results table is not coming with full string

### ISSUE THREAD

**Issue by minar09** [AutomationSolutionz/Framework_0.1#572]
after semi colon

**Comment by m3thun** [comment]
@minar09 Please give us an update of this ticket. This needs to be addressed soon as this one has the highest priority. Thanks!

**Comment by minar09** [comment]
I submitted fix for this bug few days ago.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: mithunSent: Monday, August 17, 2015 6:24 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Matiur Rahman MinarSubject: Re: [Framework_0.1] Milestone in results table is not coming with full string (#572)@minar09 Please give us an update of this ticket. This needs to be addressed soon as this one has the highest priority. Thanks!

—Reply to this email directly or view it on GitHub.

**Comment by riz-hossain** [comment]
Thanks. I guess tags weren't updated to be done.   That's why I didn't pull yet. I will pull and update.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Matiur Rahman MinarSent: Monday, August 17, 2015 8:26 AMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Subject: Re: [Framework_0.1] Milestone in results table is not coming with full string (#572)                                                                                      I submitted fix for this bug few days ago.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: mithunSent: Monday, August 17, 2015 6:24 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Matiur Rahman MinarSubject: Re: [Framework_0.1] Milestone in results table is not coming with full string (#572)@minar09 Please give us an update of this ticket. This needs to be addressed soon as this one has the highest priority. Thanks!

—Reply to this email directly or view it on GitHub.

—Reply to this email directly or view it on GitHub.

**Comment by m3thun** [comment]
@riz-hossain Please verify and close this ticket. Thanks!

**Comment by m3thun** [comment]
@minar09 When you label a ticket "Done", please remove the label "Started". They both should not be present at the same time.
@riz-hossain Did you pull yet? Please give me the update.

**Comment by riz-hossain** [comment]
I fixed the auto pulling from the server and it's working now. Thanks for the fix.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: mithunSent: Sunday, August 23, 2015 7:07 PMTo: AutomationSolutionz/Framework_0.1Reply To: AutomationSolutionz/Framework_0.1Cc: Riz HossainSubject: Re: [Framework_0.1] Milestone in results table is not coming with full string (#572)@minar09 When you label a ticket "Done", please remove the label "Started". They both should not be present at the same time.
@riz-hossain Did you pull yet? Please give me the update.

—Reply to this email directly or view it on GitHub.

**Comment by m3thun** [comment]
@riz-hossain Closing it.
